### PR TITLE
refactor: enumerable property decorator

### PR DESCRIPTION
**Pull request by cuebit**
#### Type of PR:

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Code style update
- [ ] Build-related changes
- [ ] Test
- [ ] Documentation
- [ ] Other, please describe:

#### Breaking changes:

- [x] No
- [ ] Yes

### Details

Internal decorator to configure innumerable class properties. This is particularly useful for user-end objects who's properties should not be "visible" during enumeration.

### CODE REVIEW

**Comment by cuebit** [comment]
@kiaking the question now is... how would you like me to organise a test for this? It's a very simple test, most certainly a unit test, but where would you like it to sit in the directory tree?

**Comment by kiaking** [comment]
Nice work! I think the test can go into `unit/decorators/Enumerable` directory and test only the decorator function with generic class 👍 

Also I think this decorator should be exported from `index.ts`. It's mainly for api-extractor documentation that modules used in public module, needs to be exported publicly or else it's hard to document it. But not sure how it would look like for decorator 🤔  But maybe users would still find useful for this one anyway.

**Comment by cuebit** [comment]
> Also I think this decorator should be exported from index.ts.

Oh yea, definitely. I can think of a few plugins that could make use of this. It’s a hidden gem, not something worth documenting but developers who checkout the api extractor will see it and make sense of it 👍

**Comment by cuebit** [comment]
@kiaking conflicts resolved 👍

**Pull request merged**
